/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.UsuarioDao;
import br.com.senac.dao.UsuarioDaoImpl;
import br.com.senac.entidade.Usuario;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author silvio.junior
 */
public class AlteraSenha extends javax.swing.JFrame {

    private Usuario usuario;

    public AlteraSenha() {
        initComponents();
    }

    public AlteraSenha(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        varNome.setText(usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lb_nome = new javax.swing.JLabel();
        varNome = new javax.swing.JLabel();
        lb_senhaAntiga = new javax.swing.JLabel();
        lb_novaSenha = new javax.swing.JLabel();
        lb_confirmaSenha = new javax.swing.JLabel();
        varSenhaAntiga = new javax.swing.JPasswordField();
        varSenhaNova = new javax.swing.JPasswordField();
        varConfirmaSenha = new javax.swing.JPasswordField();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altera Senha");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                teste(evt);
            }
        });

        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Altera Senha");

        lb_nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_nome.setText("Nome:");

        lb_senhaAntiga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_senhaAntiga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_senhaAntiga.setText("Senha Antiga:");

        lb_novaSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_novaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_novaSenha.setText("Nova Senha:");

        lb_confirmaSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_confirmaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_confirmaSenha.setText("Confirma Senha:");

        varSenhaAntiga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varSenhaAntigaFocusLost(evt);
            }
        });

        varSenhaNova.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varSenhaNovaFocusLost(evt);
            }
        });

        varConfirmaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varConfirmaSenhaFocusLost(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_confirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_novaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_senhaAntiga, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(lb_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(varNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varSenhaNova)
                        .addComponent(varConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(varSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senhaAntiga)
                    .addComponent(varSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_novaSenha)
                    .addComponent(varSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_confirmaSenha)
                    .addComponent(varConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAlterar)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void varSenhaAntigaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varSenhaAntigaFocusLost
        String senhaAntiga = String
                .valueOf(varSenhaAntiga.getPassword());
        if (!usuario.getSenha().equals(senhaAntiga)) {
            JOptionPane.showMessageDialog(null,
                    "Senha antiga não confere");
            varSenhaAntiga.grabFocus();
        }

    }//GEN-LAST:event_varSenhaAntigaFocusLost

    private void varSenhaNovaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varSenhaNovaFocusLost
        String senhaNova = String
                .valueOf(varSenhaNova.getPassword());

        if (usuario.getSenha().equals(senhaNova)) {
            JOptionPane.showMessageDialog(null,
                    "A nova senha não pode ser a mesma!");
            varSenhaNova.grabFocus();
        }
    }//GEN-LAST:event_varSenhaNovaFocusLost

    private void varConfirmaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varConfirmaSenhaFocusLost
        String senhaNova = String
                .valueOf(varSenhaNova.getPassword());
        String confirmaSenha = String
                .valueOf(varConfirmaSenha.getPassword());

        if (!senhaNova.equals(confirmaSenha)) {
            JOptionPane.showMessageDialog(null,
                    "As senhas não conferem");
            varConfirmaSenha.grabFocus();
        }
    }//GEN-LAST:event_varConfirmaSenhaFocusLost

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (validarFormulario()) {
            UsuarioDao usuarioDao = new UsuarioDaoImpl();
            Session sessao = HibernateUtil.abrirConexao();
            String senhaNova = String
                .valueOf(varSenhaNova.getPassword());
            usuario.setSenha(senhaNova);
            try {
                usuarioDao.salvarOuAlterar(usuario, sessao);
                new Login().setVisible(true);
                dispose();
            } catch (HibernateException e) {
                System.out.println("Erro ao salvar senha " + e.getMessage());
                new TelaPrincipal(usuario).setVisible(true);
            }finally{
                sessao.close();
            }        
            
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void teste(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_teste
        dispose();
        new TelaPrincipal(usuario).setVisible(true);
    }//GEN-LAST:event_teste

    private boolean validarFormulario() {
        String senhaAntiga = String
                .valueOf(varSenhaAntiga.getPassword());
        if (validarCampoPreenchido(senhaAntiga)) {
            JOptionPane.showMessageDialog(null,
                    "Digite a senha antiga");
            return false;
        }

        String senhaNova = String
                .valueOf(varSenhaNova.getPassword());
        if (validarCampoPreenchido(senhaNova)) {
            JOptionPane.showMessageDialog(null,
                    "Digite a senha nova");
            return false;
        }

        String confirmaSenha = String
                .valueOf(varConfirmaSenha.getPassword());
        if (validarCampoPreenchido(confirmaSenha)) {
            JOptionPane.showMessageDialog(null,
                    "Digite um valor para confirma senha");
            return false;
        }
        return true;
    }

    private boolean validarCampoPreenchido(String campo) {
        return campo.length() < 3;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JLabel lb_confirmaSenha;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_novaSenha;
    private javax.swing.JLabel lb_senhaAntiga;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPasswordField varConfirmaSenha;
    private javax.swing.JLabel varNome;
    private javax.swing.JPasswordField varSenhaAntiga;
    private javax.swing.JPasswordField varSenhaNova;
    // End of variables declaration//GEN-END:variables
}
