/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.ClienteDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.ProfissaoDao;
import br.com.senac.dao.ProfissaoDaoImpl;
import br.com.senac.entidade.Cliente;
import br.com.senac.entidade.Endereco;
import br.com.senac.entidade.Profissao;
import br.com.senac.entidade.Telefone;
import java.awt.event.FocusEvent;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import webservice.CepRest;

/**
 *
 * @author felipe.ticiani
 */
public class CadastroCliente extends javax.swing.JFrame {
    
    private Session sessao;
    private List<Profissao> profissoes;
    private Cliente cliente;
    private Telefone telefone;
    private Endereco endereco;

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        carregarComboProfissao();
        carregarComboTipo();
        btnAlterar.setVisible(false);
    }
    
    public CadastroCliente(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        carregarComboProfissao();
        varComboProfissao.setSelectedItem(cliente.getProfissao());
        carregarComboTipo();
        varComboTipo.setSelectedItem(cliente.getTelefone().getTipo());
        btnSalvar.setVisible(false);
        lblTitulo.setText("Editar Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        painel_01 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        varCPF = new javax.swing.JFormattedTextField();
        lblRG = new javax.swing.JLabel();
        varRG = new javax.swing.JTextField();
        lblProfissao = new javax.swing.JLabel();
        varComboProfissao = new javax.swing.JComboBox<>();
        lblSalario = new javax.swing.JLabel();
        varSalario = new javax.swing.JFormattedTextField();
        painel_02 = new javax.swing.JPanel();
        lblCEP = new javax.swing.JLabel();
        varCEP = new javax.swing.JFormattedTextField();
        lblLogradouro = new javax.swing.JLabel();
        varLogradouro = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        varNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JTextField();
        varComplemento = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        varBairro = new javax.swing.JTextField();
        lblLocalidade = new javax.swing.JLabel();
        varLocalidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        varUF = new javax.swing.JTextField();
        lblObservacao = new javax.swing.JLabel();
        varObservacao = new javax.swing.JTextField();
        painel_3 = new javax.swing.JPanel();
        lblTelefone = new javax.swing.JLabel();
        varTelefone = new javax.swing.JFormattedTextField();
        lblOperadora = new javax.swing.JLabel();
        varOperadora = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        varComboTipo = new javax.swing.JComboBox<>();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de cliente");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastrar Cliente");

        painel_01.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados pessoais"));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCPF.setText("CPF:");

        try {
            varCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblRG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRG.setText("RG:");

        lblProfissao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProfissao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProfissao.setText("Profissão:");

        varComboProfissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma profissão..." }));

        lblSalario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSalario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalario.setText("Salário:");

        varSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout painel_01Layout = new javax.swing.GroupLayout(painel_01);
        painel_01.setLayout(painel_01Layout);
        painel_01Layout.setHorizontalGroup(
            painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varNome))
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblProfissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varComboProfissao, 0, 252, Short.MAX_VALUE))
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_01Layout.createSequentialGroup()
                                .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_01Layout.createSequentialGroup()
                                .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_01Layout.createSequentialGroup()
                                .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painel_01Layout.setVerticalGroup(
            painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_01Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCPF)
                    .addComponent(varCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRG)
                    .addComponent(varRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(varSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalario))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfissao)
                    .addComponent(varComboProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        painel_02.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblCEP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCEP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCEP.setText("CEP:");

        try {
            varCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        varCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varCEPFocusLost(evt);
            }
        });

        lblLogradouro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLogradouro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogradouro.setText("Logradouro:");

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("Número:");

        varComplemento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        varComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        varComplemento.setText("Complemento:");

        lblBairro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBairro.setText("Bairro:");

        lblLocalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLocalidade.setText("Localidade:");

        lblUF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUF.setText("UF:");

        lblObservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblObservacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObservacao.setText("Observação:");

        javax.swing.GroupLayout painel_02Layout = new javax.swing.GroupLayout(painel_02);
        painel_02.setLayout(painel_02Layout);
        painel_02Layout.setHorizontalGroup(
            painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogradouro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addComponent(lblCEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblObservacao))
                .addGap(18, 18, 18)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_02Layout.createSequentialGroup()
                        .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblComplemento))
                    .addComponent(varLogradouro)
                    .addGroup(painel_02Layout.createSequentialGroup()
                        .addComponent(varLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varUF))
                    .addGroup(painel_02Layout.createSequentialGroup()
                        .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(varObservacao))
                .addContainerGap())
        );
        painel_02Layout.setVerticalGroup(
            painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_02Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(varCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogradouro)
                    .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumero)
                    .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varComplemento)
                        .addComponent(lblComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidade)
                    .addComponent(varLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUF))
                .addGap(18, 18, 18)
                .addGroup(painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservacao)
                    .addComponent(varObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        painel_3.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText("Telefone:");

        try {
            varTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblOperadora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOperadora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOperadora.setText("Operadora:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText("Tipo:");

        varComboTipo.setToolTipText("");

        javax.swing.GroupLayout painel_3Layout = new javax.swing.GroupLayout(painel_3);
        painel_3.setLayout(painel_3Layout);
        painel_3Layout.setHorizontalGroup(
            painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOperadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(varOperadora)
                    .addComponent(varComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varTelefone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_3Layout.setVerticalGroup(
            painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOperadora)
                    .addComponent(varOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(varComboTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnAlterar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarComboProfissao() {
        ProfissaoDao profissaoDao = new ProfissaoDaoImpl();
        try {
            sessao = HibernateUtil.abrirConexao();
            profissoes = profissaoDao.pesquisarTodosAtivos(sessao);
            profissoes.forEach(p -> varComboProfissao.addItem(p.getNome()));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            sessao.close();
        }
    }
    
    private void carregarComboTipo() {
        varComboTipo.addItem("Celular");
        varComboTipo.addItem("Fixo");
    }
   
    private boolean validarFormularioDadosPessoais() {
        if(varNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o nome!");
            return false;
        }
        if(varCPF.getText().trim().length() != 14) {
            JOptionPane.showMessageDialog(null, "Digite o CPF corretamente!");
            return false;
        }
        if(varRG.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Digite o RG!");
            return false;
        }
        if(varSalario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o salário!");
            return false;
        }
        
        if(Double.parseDouble(varSalario.getText().replace(",", ".")) <= 0) {
            JOptionPane.showMessageDialog(null, "Salário não pode ser zero!");
            return false;
        }
        if(varComboProfissao.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione a profissão!");
            return false;
        }
        return true;
    }
    
    private boolean validarFormularioTelefone() {
        if(varTelefone.getText().trim().length() != 14) {
            JOptionPane.showMessageDialog(null, "Digite o telefone corretamente!");
            return false;
        }
        if(varTelefone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a operadora!");
            return false;
        }
        return true;
    }
    
    private boolean validarFormularioEndereco() {
        if(varCEP.getText().trim().length() != 9) {
            JOptionPane.showMessageDialog(null, "Digite o CEP corretamente!");
            return false;
        }
        if(varLogradouro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o logradouro!");
            return false;
        }
        if(varNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o número!");
            return false;
        }
        if(varBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o bairro!");
            return false;
        }
        if(varLocalidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a localidade!");
            return false;
        }
        if(varUF.getText().trim().length() != 2) {
            JOptionPane.showMessageDialog(null, "Informe a UF corretamente!");
            return false;
        }
        return true;
    }
    
    private Cliente popularCliente() {
        cliente = new Cliente();
        cliente.setNome(varNome.getText());
        cliente.setCpf(varCPF.getText());
        cliente.setRg(varRG.getText());
        cliente.setSalario(Double.parseDouble(varSalario.getText().replace(",", ".")));
        return cliente;
    }
    
    private Telefone popularTelefone() {
        telefone = new Telefone();
        String ddd = varTelefone.getText().substring(1, 3);
        telefone.setDdd(ddd);
        String numero = varTelefone.getText().substring(4, 14).replace("-", "");
        telefone.setNumero(numero);
        telefone.setOperadora(varOperadora.getText());
        telefone.setTipo(varComboTipo.getSelectedItem().toString());
        return telefone;
    }
    
    private Endereco popularEndereco() {
        endereco.setLogradouro(varLogradouro.getText());
        endereco.setNumero(varNumero.getText());
        endereco.setComplemento(varComplemento.getText());
        endereco.setBairro(varBairro.getText());
        endereco.setObservacao(varObservacao.getText());
        return endereco;
    }
    
    private boolean validarCampoCEP() {
        if (varCEP.getText().trim().length() != 9) {
            JOptionPane.showMessageDialog(null, "Digite o CEP corretamente!");
            return false;
        }
        return true;
    }
    
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (validarFormularioDadosPessoais() && validarFormularioTelefone() && validarFormularioEndereco()) {
            try {
                sessao = HibernateUtil.abrirConexao();
                cliente = popularCliente();
                cliente.setTelefone(popularTelefone());
                cliente.setEndereco(popularEndereco());
                cliente.setProfissao(profissoes.get(varComboProfissao.getSelectedIndex() - 1));
                new ClienteDaoImpl().salvarOuAlterar(cliente, sessao);
                JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso!");
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar cliente!");
            } finally {
                sessao.close();
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (validarFormularioDadosPessoais() && validarFormularioTelefone() && validarFormularioEndereco()) {
            try {
                sessao = HibernateUtil.abrirConexao();
                cliente = popularCliente();
                cliente.setTelefone(popularTelefone());
                cliente.setEndereco(popularEndereco());
                cliente.setProfissao(profissoes.get(varComboProfissao.getSelectedIndex() - 1));
                new ClienteDaoImpl().salvarOuAlterar(cliente, sessao);
                JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso!");
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar cliente!");
            } finally {
                sessao.close();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void varCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varCEPFocusLost
        if (validarCampoCEP()) {
            CepRest cepRest = new CepRest();
            endereco = cepRest.pesquisaCep(varCEP.getText().replace("-", ""));
            if (endereco.getLogradouro() == null) {
                JOptionPane.showMessageDialog(null, "CEP não encontrado!");
            } else {
                varLogradouro.setText(endereco.getLogradouro());
                varBairro.setText(endereco.getBairro());
                varLocalidade.setText(endereco.getLocalidade());
                varLocalidade.setEnabled(false);
                varUF.setText(endereco.getUf());
                varUF.setEnabled(false);
            }
        }
    }//GEN-LAST:event_varCEPFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JTextField lblComplemento;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblOperadora;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUF;
    private javax.swing.JPanel painel_01;
    private javax.swing.JPanel painel_02;
    private javax.swing.JPanel painel_3;
    private javax.swing.JTextField varBairro;
    private javax.swing.JFormattedTextField varCEP;
    private javax.swing.JFormattedTextField varCPF;
    private javax.swing.JComboBox<String> varComboProfissao;
    private javax.swing.JComboBox<String> varComboTipo;
    private javax.swing.JLabel varComplemento;
    private javax.swing.JTextField varLocalidade;
    private javax.swing.JTextField varLogradouro;
    private javax.swing.JTextField varNome;
    private javax.swing.JTextField varNumero;
    private javax.swing.JTextField varObservacao;
    private javax.swing.JTextField varOperadora;
    private javax.swing.JTextField varRG;
    private javax.swing.JFormattedTextField varSalario;
    private javax.swing.JFormattedTextField varTelefone;
    private javax.swing.JTextField varUF;
    // End of variables declaration//GEN-END:variables
}
